"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { money, totals, validSplit } from "@/lib/calculations";
import { PEOPLE, Role, Sale, Expense, Split, Allocation } from "@/lib/types";

const initialSplit: Split = { richard: 50, anastasia: 30, jean_claude: 20 };
const labels: Record<string, string> = { A: "Respectable Relatives", B: "Drunk University Friends", overhead: "Company overhead", awaiting_allocation: "Awaiting allocation", pending: "Pending approval", allocated: "Allocated", approved: "Approved" };
const splitFields: (keyof Split)[] = ["richard", "anastasia", "jean_claude"];

export default function Home() {
  const [role, setRole] = useState<Role>("richard"); const [sales, setSales] = useState<Sale[]>([]); const [expenses, setExpenses] = useState<Expense[]>([]); const [employees, setEmployees] = useState<any[]>([]); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true);
  const refresh = async () => { setLoading(true); const r = await fetch("/api/dashboard", { cache: "no-store" }); if (r.ok) { const d = await r.json(); setSales(d.sales); setExpenses(d.expenses); setEmployees(d.employees); } else setNotice("Could not load records. Check the Supabase connection."); setLoading(false); };
  useEffect(() => { fetch("/api/demo-role", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ role: "richard" }) }); refresh(); }, []);
  const chooseRole = async (nextRole: Role) => { setRole(nextRole); const result = await fetch("/api/demo-role", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ role: nextRole }) }); if (!result.ok) setNotice("Could not update demonstration role."); };
  const summary = useMemo(() => totals(sales, expenses), [sales, expenses]);
  const call = async (url: string, payload: unknown) => { const r = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const d = await r.json(); setNotice(d.error || (d.notification?.ok === false ? `Saved. Notification: ${d.notification.reason}` : "Saved beautifully.")); if (r.ok) refresh(); return r.ok; };
  return <main>
    <header className="topbar"><div className="brand"><span className="heart">♥</span><div><b>Friends Included</b><small>Wedding guest finance</small></div></div><div className="role-picker"><label>Demonstration role</label><select value={role} onChange={(e) => chooseRole(e.target.value as Role)}>{Object.entries(PEOPLE).map(([key, person]) => <option key={key} value={key}>{person.name} · {person.title}</option>)}</select></div></header>
    <section className="hero"><p className="eyebrow">All friendships expire at checkout</p><h1>Make every <i>moment</i> count.</h1><p>A small, clear control room for hired guests, dramatic entrances, and financial decisions.</p><div className="hero-links"><a href={process.env.NEXT_PUBLIC_TELEGRAM_BOT_USERNAME ? `https://t.me/${process.env.NEXT_PUBLIC_TELEGRAM_BOT_USERNAME}` : "#setup"}>Open Telegram bot ↗</a><a href={process.env.NEXT_PUBLIC_GOOGLE_SHEETS_URL || "https://docs.google.com/spreadsheets/d/1yuaoLEEfhntBpCScGB8I0wMmLpfuvbIcVQxSVEvJJQM/edit"} target="_blank" rel="noreferrer">Open shared ledger ↗</a><a href="#records">View records</a></div></section>
    {notice && <div className="notice" onClick={() => setNotice("")}>{notice} <span>×</span></div>}
    <section className="dashboard"><p className="eyebrow">Live position</p><h2>A gentle overview</h2><div className="metric-grid"><Metric title="Project A result" value={money(summary.A.result)} note="Respectable Relatives" /><Metric title="Project B result" value={money(summary.B.result)} note="Drunk University Friends" /><Metric title="Company result" value={money(summary.company)} note={`${money(summary.overhead)} overhead · ${money(summary.awaiting)} awaiting`} /><Metric title="Commissions earned" value={money(summary.commissions.total)} note="Approved sales only" /></div></section>
    <section className="workspace"><div className="entry-panel"><p className="eyebrow">New transaction</p><h2>{role === "kevin" ? "Record an expense" : role === "svetlana" ? "Manager controls" : "Record a sale"}</h2>{role === "kevin" ? <ExpenseForm role={role} call={call} /> : role === "svetlana" ? <ManagerSetup call={call} employees={employees} /> : <SaleForm role={role} call={call} />}</div><aside className="howto"><p className="eyebrow">How it works</p><ol><li>Choose a demonstration role.</li><li>Enter a sale or expense.</li><li>Svetlana approves decisions.</li><li>Records, totals, Sheets, and Telegram stay aligned.</li></ol><p className="tiny">Website and bot use the same validation and calculation rules. Secrets stay server-side.</p></aside></section>
    <section className="projects"><ProjectCard title="Respectable Relatives" subtitle="Project A" values={summary.A} tone="rose" /><ProjectCard title="Drunk University Friends" subtitle="Project B" values={summary.B} tone="lilac" /></section>
    <section className="manager verification" aria-label="Integration verification"><div className="section-head"><div><p className="eyebrow">Integration verification</p><h2>Webhook repair evidence</h2></div><a className="ghost" href={process.env.NEXT_PUBLIC_GOOGLE_SHEETS_URL || "https://docs.google.com/spreadsheets/d/1yuaoLEEfhntBpCScGB8I0wMmLpfuvbIcVQxSVEvJJQM/edit"} target="_blank" rel="noreferrer">Open matching ledger ↗</a></div><p>Verified 30 September 2026: valid Telegram expense messages E93007 and E93008 each produced one reply and one Google Sheets row.</p><div className="linked"><span><b>E93007</b> · €3.00 · Project A proposal · one recorded reply</span><span><b>E93008</b> · €4.00 · Project B proposal · one recorded reply</span></div><p className="tiny">The checks used fictional data. The original assignment company result is €3,930 before these €7.00 test expenses, and pending S05 and E07 were not changed. No repeated reply was observed for either verified message.</p></section>
    <section className="manager" id="records"><div className="section-head"><div><p className="eyebrow">Decisions and records</p><h2>Keep the story straight</h2></div><button className="ghost" onClick={refresh}>Refresh</button></div>{loading ? <p>Loading the guest list…</p> : <><Pending role={role} sales={sales.filter(s => s.status === "pending")} expenses={expenses.filter(e => e.status === "awaiting_allocation")} call={call} /><Records sales={sales} expenses={expenses} /></>}</section>
    <section className="commissions"><p className="eyebrow">Commission earned</p><div>{(["richard", "anastasia", "jean_claude"] as const).map(person => <span key={person}><b>{money(summary.commissions[person])}</b>{PEOPLE[person].name}</span>)}</div></section>
    <footer><b>Friends Included Ltd</b><span>Fictional people. Real accounting rules. · <a href="#setup">Setup guide</a></span></footer>
  </main>;
}
function Metric({ title, value, note }: { title: string; value: string; note: string }) { return <article className="metric"><span>{title}</span><strong>{value}</strong><small>{note}</small></article>; }
function ProjectCard({ title, subtitle, values, tone }: any) { return <article className={`project ${tone}`}><p>{subtitle}</p><h3>{title}</h3><dl><div><dt>Approved income</dt><dd>{money(values.income)}</dd></div><div><dt>Commission expense</dt><dd>{money(values.commissions)}</dd></div><div><dt>Allocated expenses</dt><dd>{money(values.allocatedExpenses)}</dd></div><div className="result"><dt>Result</dt><dd>{money(values.result)}</dd></div></dl></article>; }
function SaleForm({ role, call }: { role: Role; call: Function }) { const [split, setSplit] = useState<Split>(initialSplit); const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); if (!validSplit(split)) return; if (await call("/api/sales", { role, reference: f.get("reference"), customer: f.get("customer"), project: f.get("project"), description: f.get("description"), amount: f.get("amount"), proposed_split: split })) e.currentTarget.reset(); }; return <form onSubmit={submit}><Field label="Reference" name="reference" placeholder="e.g. S06" /><Field label="Customer" name="customer" placeholder="Their happy name" /><label>Project<select name="project"><option value="A">A · Respectable Relatives</option><option value="B">B · Drunk University Friends</option></select></label><Field label="Description" name="description" placeholder="What are we providing?" /><Field label="Amount (€)" name="amount" type="number" step="0.01" min="0.01" /><fieldset><legend>Proposed commission split <em>{Object.values(split).reduce((a,b) => a + b, 0)}%</em></legend><div className="split">{splitFields.map(key => <label key={key}>{PEOPLE[key].name}<input type="number" min="0" max="100" value={split[key]} onChange={e => setSplit({ ...split, [key]: Number(e.target.value) })} />%</label>)}</div></fieldset><button className="primary" disabled={!validSplit(split)}>Submit sale</button></form>; }
function ExpenseForm({ role, call }: { role: Role; call: Function }) { const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); if (await call("/api/expenses", { role, reference: f.get("reference"), description: f.get("description"), category: f.get("category"), amount: f.get("amount"), proposed_allocation: f.get("allocation") })) e.currentTarget.reset(); }; return <form onSubmit={submit}><Field label="Reference" name="reference" placeholder="e.g. E08" /><Field label="Description" name="description" placeholder="Costume, transport, etc." /><label>Category<select name="category"><option>Materials</option><option>Travel</option><option>Other</option></select></label><Field label="Amount (€)" name="amount" type="number" step="0.01" min="0.01" /><label>Proposed allocation<select name="allocation"><option value="A">A · Respectable Relatives</option><option value="B">B · Drunk University Friends</option><option value="overhead">Company overhead</option></select></label><button className="primary">Submit expense</button></form>; }
function Field({ label, ...props }: any) { return <label>{label}<input required {...props} /></label>; }
function ManagerSetup({ call, employees }: { call: Function; employees: any[] }) { const [open, setOpen] = useState(false); const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); if (await call("/api/manager/link", { role: "svetlana", employee_role: f.get("employee_role"), telegram_user_id: f.get("telegram_user_id"), telegram_chat_id: f.get("telegram_chat_id") })) e.currentTarget.reset(); }; return <><p className="manager-copy">Approve the decisions below, or link a staff member’s Telegram identity for bot submissions and notifications.</p><button className="ghost" type="button" onClick={() => setOpen(!open)}>Link Telegram employee</button>{open && <form onSubmit={submit}><label>Employee<select name="employee_role">{Object.entries(PEOPLE).map(([key, value]) => <option value={key} key={key}>{value.name}</option>)}</select></label><Field label="Telegram user ID" name="telegram_user_id" /><Field label="Telegram chat ID" name="telegram_chat_id" /><button className="primary">Save Telegram link</button></form>}<div className="linked">{employees.map(e => <span key={e.role}>{PEOPLE[e.role as Role]?.name}: {e.telegram_chat_id ? "linked" : "not linked"}</span>)}</div></>; }
function Pending({ role, sales, expenses, call }: { role: Role; sales: Sale[]; expenses: Expense[]; call: Function }) { return <div className="pending"><h3>Awaiting Svetlana</h3>{!sales.length && !expenses.length && <p className="quiet">Nothing needs a decision right now.</p>}{sales.map(s => <SaleDecision key={s.id} sale={s} role={role} call={call} />)}{expenses.map(e => <ExpenseDecision key={e.id} expense={e} role={role} call={call} />)}</div>; }
function SaleDecision({ sale, role, call }: { sale: Sale; role: Role; call: Function }) { const [split, setSplit] = useState<Split>(sale.proposed_split); return <article className="decision"><div><span className="status">Pending sale</span><h4>{sale.reference} · {money(sale.amount)}</h4><p>{sale.customer} · Project {sale.project} · {sale.description}</p></div><div className="decision-controls">{splitFields.map(key => <label key={key}>{key.replace("_", " ")}<input disabled={role !== "svetlana"} type="number" value={split[key]} onChange={e => setSplit({...split,[key]:Number(e.target.value)})}/>%</label>)}<button className="primary" disabled={role !== "svetlana" || !validSplit(split)} onClick={() => call("/api/decisions/sale", { role, id: sale.id, approved_split: split })}>Approve sale</button></div></article>; }
function ExpenseDecision({ expense, role, call }: { expense: Expense; role: Role; call: Function }) { const [allocation, setAllocation] = useState<Allocation>(expense.proposed_allocation); return <article className="decision"><div><span className="status">Awaiting allocation</span><h4>{expense.reference} · {money(expense.amount)}</h4><p>{expense.description} · {expense.category} · Proposed: {labels[expense.proposed_allocation]}</p></div><div className="decision-controls"><select disabled={role !== "svetlana"} value={allocation} onChange={e=>setAllocation(e.target.value as Allocation)}><option value="A">Project A</option><option value="B">Project B</option><option value="overhead">Company overhead</option></select><button className="primary" disabled={role !== "svetlana"} onClick={() => call("/api/decisions/expense", { role, id: expense.id, final_allocation: allocation })}>Confirm allocation</button></div></article>; }
function Records({ sales, expenses }: { sales: Sale[]; expenses: Expense[] }) { return <div className="records"><h3>Sales</h3><div className="table-wrap"><table><thead><tr><th>Reference</th><th>Customer</th><th>Project</th><th>Amount</th><th>Status</th><th>Sync</th></tr></thead><tbody>{sales.map(s=><tr key={s.id}><td>{s.reference}</td><td>{s.customer}</td><td>{s.project}</td><td>{money(s.amount)}</td><td>{labels[s.status]}</td><td>{s.sync_status}</td></tr>)}</tbody></table></div><h3>Expenses</h3><div className="table-wrap"><table><thead><tr><th>Reference</th><th>Description</th><th>Allocation</th><th>Amount</th><th>Status</th><th>Sync</th></tr></thead><tbody>{expenses.map(e=><tr key={e.id}><td>{e.reference}</td><td>{e.description}</td><td>{labels[e.final_allocation ?? e.proposed_allocation]}</td><td>{money(e.amount)}</td><td>{labels[e.status]}</td><td>{e.sync_status}</td></tr>)}</tbody></table></div></div>; }
